src/Entity/Config.php
<?php

namespace App\Entity;

use App\Repository\ConfigRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ConfigRepository::class)
 */
class Config
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $color;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $staff_name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isSet;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(?string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getStaffName(): ?string
    {
        return $this->staff_name;
    }

    public function setStaffName(?string $staff_name): self
    {
        $this->staff_name = $staff_name;

        return $this;
    }

    public function getIsSet(): ?bool
    {
        return $this->isSet;
    }

    public function setIsSet(bool $isSet): self
    {
        $this->isSet = $isSet;

        return $this;
    }
}

src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MessageRepository::class)
 */
class Message
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity=Ticket::class, inversedBy="MessageList")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ticketTarget;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="UserMessageList")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Author;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getTicketTarget(): ?Ticket
    {
        return $this->ticketTarget;
    }

    public function setTicketTarget(?Ticket $ticketTarget): self
    {
        $this->ticketTarget = $ticketTarget;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\TicketType;
use App\Entity\Ticket;
use App\Entity\User;
use Symfony\Component\HttpFoundation\Request;
use \DateTime;
use App\Entity\Message;
use App\Form\CreateMessageType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use App\Form\AddPhotoType;
use App\Form\UpdateNameType;
use App\Form\ConfigType;
use App\Entity\Config;
use App\Form\StaffType;


class MainController extends AbstractController
{
    /**
     * @Route("/", name="main_home")
     */
    public function index(): Response
    {

        // redirects to the "login" route
        return $this->redirectToRoute('app_login');

        return $this->render('main/index.html.twig', [
            'controller_home' => 'Page d\'acceuil',
        ]);
    }

    /**
     * @Route("/article", name="article")
     */
    public function article(): Response
    {   $repository = $this->getDoctrine()->getRepository(Config::class);
        $actualConfig = $repository->findOneBy(array(),array('id'=>'ASC'),1,0);

        return $this->render('main/article.html.twig', [
            'controller_article' => 'Page article',
            'config' => $actualConfig,
        ]);
    }

    /**
     * @Route("/dashboard/admin", name="dash_admin")
     * @Security("is_granted('ROLE_ADMIN')")
     */
    public function dash_admin(): Response
    {   
        $repository = $this->getDoctrine()->getRepository(Config::class);
        $actualConfig = $repository->findOneBy(array(),array('id'=>'ASC'),1,0);

        $ticketRepo = $this->getDoctrine()->getRepository(Ticket::class);


        //Récupération des tickets répondus
        $ticketsAnswered = $ticketRepo->findBy(['statement' => 'répondu'], ['level' => 'DESC','updateTime' => 'ASC']);

        //Récupération des tickets en attente
        $ticketsPending = $ticketRepo->findBy(['statement' => 'en attente'], ['level' => 'DESC','updateTime' => 'ASC']);

        //Récupération des tickets fermés
        $ticketsClosed = $ticketRepo->findBy(['statement' => 'fermé'], ['updateTime' => 'DESC']);


        return $this->render('main/dash_admin.html.twig', [
            'controller_dash_admin' => 'Page administrateur',
            'ticketsAnswered' => $ticketsAnswered,
            'ticketsPending' => $ticketsPending,
            'ticketsClosed' => $ticketsClosed,
            'config' => $actualConfig,
        ]);
    }

    /**
     * @Route("/dashboard", name="dash_client")
     */
    public function dash_client(): Response
    {

        
        $repository = $this->getDoctrine()->getRepository(Config::class);
        $actualConfig = $repository->findOneBy(array(),array('id'=>'ASC'),1,0);

        //Récupération de l'id de l'utilisateur connecté
        $userId = $this->getUser()->getId();
        $userRoles = $this->getUser()->getRoles();

        dump($userId);

        //Doctrine repository
        $ticketRepo = $this->getDoctrine()->getRepository(Ticket::class);

        //Récupération des tickets répondus du client connecté
        $ticketsAnsweredClient = $ticketRepo->findby(['owner' => $userId , 'statement' => 'répondu'],['level' => 'DESC','updateTime' => 'DESC']);

        //Récupération des tickets en attente du client connecté
        $ticketsPendingClient = $ticketRepo->findby(['owner' => $userId , 'statement' => 'en attente'],['level' => 'DESC','updateTime' => 'DESC']);

        //Récupération des tickets fermés du client connecté
        $ticketsClosedClient = $ticketRepo->findby(['owner' => $userId , 'statement' => 'fermé'],['updateTime' => 'DESC']);

        //Si l'utilisateur à le rôle admin, on le redirige vers le dashboard admin
        if ($userRoles[0] == 'ROLE_ADMIN') {
            return $this->redirectToRoute('dash_admin');
        };

        return $this->render('main/dash_client.html.twig', [
            'controller_dash_client' => 'Page client',
            'ticketsAnsweredClient' => $ticketsAnsweredClient,
            'ticketsPendingClient' => $ticketsPendingClient,
            'ticketsClosedClient' => $ticketsClosedClient,
            'config' => $actualConfig,
        ]);
    }

    /**
     * @Route("/faq", name="koala_faq")
     */
    public function faq(): Response
    {
        $repository = $this->getDoctrine()->getRepository(Config::class);
        $actualConfig = $repository->findOneBy(array(),array('id'=>'ASC'),1,0);

        return $this->render('main/faq.html.twig', [
            'controller_faq' => 'Page faq',
            'config' => $actualConfig,
        ]);
    }

     /**
     * Page permettant de créer un nouveau ticket
     *
     * @Route("/creer-un-ticket", name="create_ticket")
     */
    public function createTicket(Request $request): Response
    {

        $repository = $this->getDoctrine()->getRepository(Config::class);
        $actualConfig = $repository->findOneBy(array(),array('id'=>'ASC'),1,0);

        $user = $this->getUser();
        // Création d'un nouvel objet de la classe Ticket, vide pour le moment
        $newTicket = new Ticket();

        $form = $this->createForm(TicketType::class, $newTicket);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

             // defaut time zone
             date_default_timezone_set('Europe/Paris');

             // Set creation_date
             $newTicket->setCreationDate(
                new DateTime()
            );

             // Set update_time
             $newTicket->setUpdateTime(
                new DateTime()
            );

            //Set owner
            $newTicket->setOwner(
                $this->getUser()
            );

            // récupération du manager des entités et sauvegarde en BDD de $newTicket
            $em = $this->getDoctrine()->getManager();
            $em->persist($newTicket);
            $em->flush();

                //Creation du message de succès
                $this->addFlash('newTicketSuccess', 'Ticket créé avec succès !');

            // Redirection sur le ticket crée
            return $this->redirectToRoute('view_ticket', array('slug' => $newTicket->getSlug()));
        }



        return $this->render('main/ticket.html.twig', [
            'form' => $form->createView(),
            'config' => $actualConfig,
        ]);

    }

    /**
     * Page affichage ticket et réponses
     *
     * @Route("/voir-le-ticket/{slug}", name="view_ticket"))
     */
    public function CreateMessage(Ticket $ticket, Request $request) : response
    {
        $repository = $this->getDoctrine()->getRepository(Config::class);
        $actualConfig = $repository->findOneBy(array(),array('id'=>'ASC'),1,0);

        $userId = $this->getUser()->getId();

        //Récupération des repository
        $messageRepo = $this->getDoctrine()->getRepository(Message::class);
        $ticketInfo = $this->getDoctrine()->getRepository(Ticket::class);
        $userInfo = $this->getDoctrine()->getRepository(User::class);

        $messageInfo = $messageRepo->FindBy(['id' => $ticket]);
        $actualTicket = $ticketInfo->findOneBy(['id' => $ticket]);
        $authorOfTicket = $userInfo->findby(['id' => $userId]);

        //Récupération de tous les messages concernant un ticket
        $messageConversation = $messageRepo->findBy(['ticketTarget' => $actualTicket->getId()]); // 6 array
        $lastMessageId = $messageRepo->findOneBy(['ticketTarget' => $actualTicket], ['id' => 'desc']); // Dernier message

        // Récupération du statut actuel du ticket
        $actualStatement = $actualTicket->getStatement();

        // Création du formulaire
        $newMessage = new Message();
        $newTicket = new Ticket();
        $form = $this->createForm(CreateMessageType::class, $newMessage);

        // Envoi du formulaire
        $form->handleRequest($request);

        //Si le formulaire est esnvoyé et valide on hydrate
        if($form->isSubmitted() && $form->isValid()){

            date_default_timezone_set('Europe/Paris');

            $newMessage->setDate(new DateTime());
            $newMessage->setTicketTarget($ticket);
            $newMessage->setAuthor($this->getUser());

            $em = $this->getDoctrine()->getManager();
            $em->persist($newMessage);
            $em->flush();

            $actualTicket->setUpdateTime(
                new DateTime()
            );

            $em->flush();

            //Rechargement de la page pour afficher les nouveaux messages
            return $this->redirect($request->getUri());

        }

        if ($actualStatement != 'fermé' && isset($lastMessageId)) {

            // Récupération du rôle du dernier autheur du dernier message
            $lastAuthorRole = $lastMessageId->getAuthor()->getRoles();

            //Changement du statut du ticket en fonction du répondant
            if ($lastAuthorRole[0] == "ROLE_ADMIN") {
                $actualTicket->setStatement("répondu");
            } else {
                $actualTicket->setStatement("en attente");
            }

            // Envoi du tout
            $em = $this->getDoctrine()->getManager();
            $em->persist($actualTicket);
            $em->flush();
        }


        return $this->render('main/viewTicket.html.twig', [
            'form' => $form->createView(),
            'actualTicket' => $actualTicket,
            'authorOfTicket' => $authorOfTicket,
            'messageInfo' => $messageInfo,
            'messageConversation' => $messageConversation,
            'config' => $actualConfig,
        ]);
    }

    /**
     * Page permettant de fermer un ticket
     *
     * @Route("/fermer/{slug}/", name="close_ticket")
     */
    public function closeTicket(Ticket $ticket, Request $request): Response
    {

templates/main/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nom de l'Article{% endblock %}

{% block body %}

<!-- Page d'un Article-->
<main>
    <h1 class="title-page-article">Nom de l'Article</h1>
    <a class="link-all-articles" href="#">Retour à la liste des articles</a>
    <div class="article-page">
        <p class="header-page-article">- Publié le 15/02/2021 à 18h45 par Auteur</p>
        <div class="body-card-article">
            <h3>Titre de l'article</h3>
            <p>Corps de l'article : Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, totam vitae? Nulla rem itaque maxime odio. Quis esse, quaerat iure itaque harum sint perferendis cum debitis autem dolores, eligendi ut.</p>
        </div>
    </div>

    <h2 class="title-h2-article">Commentaires (Nombres)</h2>
    <div class="comments-article">
        <p class="header-page-article">- Ajouté par AUTEUR le DATE</p>
        <div class="body-card-article">
            <p>Contenu du commentaire : Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, totam vitae? Nulla rem itaque maxime odio. Quis esse, quaerat iure itaque harum sint perferendis cum debitis autem dolores, eligendi ut.</p>
        </div>
    </div>

    <div class="comments-article">
        <p class="header-page-article">- Ajouté par AUTEUR le DATE</p>
        <div class="body-card-article">
            <p>Contenu du commentaire : Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, totam vitae? Nulla rem itaque maxime odio. Quis esse, quaerat iure itaque harum sint perferendis cum debitis autem dolores, eligendi ut.</p>
        </div>
    </div>

    <div class="comments-article">
        <p class="header-page-article">- Ajouté par AUTEUR le DATE</p>
        <div class="body-card-article">
            <p>Contenu du commentaire : Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, totam vitae? Nulla rem itaque maxime odio. Quis esse, quaerat iure itaque harum sint perferendis cum debitis autem dolores, eligendi ut.</p>
        </div>
    </div>

    <div class="comments-article">
        <p class="header-page-article">- Ajouté par AUTEUR le DATE</p>
        <div class="body-card-article">
            <p>Contenu du commentaire : Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, totam vitae? Nulla rem itaque maxime odio. Quis esse, quaerat iure itaque harum sint perferendis cum debitis autem dolores, eligendi ut.</p>
        </div>
    </div>
</main>

{% endblock %}

templates/main/config.html.twig
{% extends 'base.html.twig' %}

{% block title %}Configuration du site{% endblock %}

{% block articles %}

<!--Message popup succes-->
        <div class="popupSuccess">
        {% for message in app.flashes('presetSite') %}
        <div class="success-div swashOut">{{ message }}</div>
        {% endfor %}
        </div>

<div class="line_horizontal"></div>
        <div class="head_ticket">
            <div class="head_ticket_btn">
                <div class="ticket_title">
                    <p>Configuration de votre système ticket</p>
                </div>
                 <div class="btn_box">
                    <a class="primary_btn_white" href="{{ path('dash_client')}}">Retour</a>
                </div>
            </div>
        </div>

{% endblock %}

{% block body %}
    <section class="statut_top">
        <div class="statut" id="statut">
            <div class="statut_text">
                <p>Personnalisez votre système.</p>
                <p>Le copyright n'est pas modifiable.</p>
            </div>
        </div>
    </section>

    <section class="formPictureFull">
        <div class="profile_update_box">   
            <div class="formPicture">
                <form name="config" method="post" enctype="multipart/form-data" style="width: 100%;">
                    <div class="formAll">
                        <div class="labelInput">
                            <p>Nom de votre site</p>
                        </div>
                        <div class="login_input_full">
                            <i class="fas fa-bookmark"></i>
                            <input type="text" id="config_name" name="config[name]" required="required" class="login_input" placeholder="Nom du site" value="{% if config == null %}{% else %}{{config.name}}{% endif %}">
                        </div>
                    </div>
                    <div class="formAll">
                        <div class="labelInput">
                            <p>Logo de votre site</p>
                        </div>
                        <div class="login_input_full">
                            {% if config == null %}
                            {% else %}
                            <img src="{{asset(config.logo)}}" class="configImg">
                            {% endif %}
                            <input type="file" id="config_logo" name="config[logo]" class="login_input" style="{% if config == null %}{% else %} text-align: end; {% endif %}" value="{% if config == null %}{% else %}{{config.logo}}{% endif %}">
                        </div>
                    </div>
                    <div class="formAll">
                        <div class="labelInput">
                            <p>Couleur secondaire</p>
                        </div>
                        <div class="login_input_full">
                            <i class="fas fa-eye-dropper"></i>
                            <input type="text" id="config_color" name="config[color]" required="required" class="login_input" placeholder="Couleur HEXA, laissez vide pour garder l'actuelle" value="{% if config == null %}{% else %}{{config.color}}{% endif %}">
                        </div>
                    </div>
                    <div class="formAll">
                        <div class="labelInput">
                            <p>Nom du staff</p>
                        </div>
                        <div class="login_input_full">
                            <i class="fas fa-users"></i>
                            <input type="text" id="config_staff_name" name="config[staff_name]" required="required" class="login_input" placeholder="Le nom de votre équipe" value="{% if config == null %}{% else %}{{config.staffName}}{% endif %}">
                        </div>
                    </div>
                    <div>
                        {{ form_row(form._token) }}
                    </div>
                    <button type="submit" id="config_save" name="config[save]" class="login_button input_size_ticket" style="{% if config == null %}{% else %}background-color:{{config.color}};{% endif %}">Valider</button>
                </form>
            </div>
            <div class="formPicture marginPictureBox">
                <div class="ticket_information_box no_top_margin">
                    <p>Ajoutez des membres à votre équipe</p>
                    <a href="{{path('addusers')}}" class="primary_btn_success" style="{% if config == null %}{% else %}background-color:{{config.color}};{% endif %}">Ajouter</a>
                </div>
                <div class="ticket_information_box">
                    <p>Liste des membres de votre équipe</p>
                    <a href="{{path('addusers')}}" class="primary_btn_success" style="{% if config == null %}{% else %}background-color:{{config.color}};{% endif %}">Voir la liste</a>
                </div>
                <div class="ticket_information_box">
                    <p>Activer le mode maintenance</p>
                    <a href="{{path('addusers')}}" class="primary_btn_success" style="{% if config == null %}{% else %}background-color:{{config.color}};{% endif %}">Maintenance</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/laragon/www/project/src/Controller/MainController.php'|file_link(0) }}">src/Controller/MainController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/laragon/www/project/templates/main/index.html.twig'|file_link(0) }}">templates/main/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/main/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer un ticket{% endblock %}

{% block articles %}

<!-- Affichage message de succes -->

            <div class="popupSuccess">
            {% for message in app.flashes('photoSuccess') %}
            <div class="success-div swashOut">{{ message }}</div>
            {% endfor %}
            </div>

<div class="line_horizontal"></div>
        <div class="head_ticket">
            <div class="head_ticket_btn">
                <div class="ticket_title">
                    <p>Mettez à jour votre profil</p>
                </div>
                 <div class="btn_box">
                    <a class="primary_btn_white" href="{{ path('dash_client')}}">Retour</a>
                </div>
            </div>
        </div>

{% endblock %}

{% block body %}
<section class="statut_top">
        <div class="statut" id="statut">
            <div class="statut_text">
                <p>Aucune grâce extérieure n'est complète si la beauté intérieure ne la vivifie.</p>
                <p>La beauté de l'âme se répand comme une lumière mystérieuse sur la beauté du corps.</p>
            </div>
        </div>
    </section>
    <section class="formPictureFull">
        <div class="profile_update_box">
            <div class="formPicture">
                <h2>Photo de Profil</h2>
                    {% if (app.user.picture == null) %}
                    <img src="{{ asset('images/default.png') }}" alt="" class="profil_picture_profil">
                    {% else %}
                    <img src="{{ asset(app.user.picture) }}" alt="" class="profil_picture_profil">
                    {% endif %}
                <form name="add_photo" method="post" enctype="multipart/form-data" style="width: 100%;">
                    <div class="input_file_type">
                        {{ form_widget(form.photo) }}
                    </div>
                    <div>
                        {{ form_row(form._token) }}
                    </div>
                    <button type="submit" class="login_button input_size_ticket" style="{% if config == null %}{% else %}background-color:{{config.color}};{% endif %}">Mettre à jour</button>
                </form>
            </div>
            <div class="formPicture marginPictureBox">
                <img src="{{asset('images/profil.svg')}}" alt="photo de profil">
            </div>
        </div>
    </section>
{% endblock %}

templates/main/viewTicket.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voir mon ticket{% endblock %}

{% block articles %}
    <!-- Message popup success-->
        <div class="popupSuccess">
        {% for message in app.flashes('newTicketSuccess') %}
        <div class="success-div swashOut">{{ message }}</div>
        {% endfor %}
        </div>

<div class="line_horizontal"></div>
        <div class="head_ticket">
            <div class="head_ticket_title">
                <h2>Ticket #{{ actualTicket.id }}</h2>
            </div>
            <div class="head_ticket_btn">
                <div class="ticket_title">
                    <p>{{ actualTicket.title }}</p>
                </div>
                 <div class="btn_box">
                    <a class="primary_btn_white" href="{{ path('dash_client')}}">Retour</a>
                    {% if actualTicket.statement != 'fermé' %}
                    <a onclick="return confirm('Êtes-vous sûr de vouloir fermer ce ticket ?')" class="primary_btn_red" href="{{ path('close_ticket' , {'slug': actualTicket.slug}) }}">Fermer le ticket</a>
                    {% endif %}
                </div>
            </div>
        </div>

{% endblock %}

{% block body %}

<section class="statut_top">
        <div class="statut statut_reset" id="statut">
            <div class="statut_text statut_width">

        {# Affichage du contenu du premier ticket #}
                <div class="client_response">
                    <div class="client_response_header">
                        <div class="client_ticket_info_box">
                            <div>
                                {% if (actualTicket.Owner.picture == null) %}
                                <img src="{{ asset('images/default.png') }}" alt="" class="ticket_img">
                                {% else %}
                                <img src="{{ asset(actualTicket.Owner.picture) }}" alt="" class="ticket_img">
                                {% endif %}
                            </div>
                            <div class="client_info">
                                <p>{{actualTicket.Owner.firstname}} {{actualTicket.Owner.lastname}}</p>
                                <p>Client</p>
                            </div>
                        </div>
                        <div>
                            <p class="response_date" style="{% if config == null %}{% else %}background-color:{{config.color}};{% endif %}">{{actualTicket.creationDate|date('d/m/Y à H\\hi')}}</p>
                        </div>
                    </div>
                    <div class="ticket_line"></div>
                    <div class="ticket_client_message">
                        <p>{{actualTicket.content|nl2br}}</p>
                    </div>
                </div>
        {# Affichage du contenu du premier ticket #}




        {% for MessageDisplay in messageConversation %}
            {# Affichage d'une boite de message #}
            {% if MessageDisplay.author.roles[0] == 'ROLE_ADMIN' %}
                <div class="client_response" style="{% if config == null %}{% else %}background-color:{{config.color}};color:white;{% endif %}">
            {% else %}
                <div class="client_response">
            {% endif %}
                    <div class="client_response_header">
                        <div class="client_ticket_info_box">
                            <div>
                                {% if (MessageDisplay.author.picture == null) %}
                                <img src="{{ asset('images/default.png') }}" alt="" class="ticket_img">
                                {% else %}
                                <img src="{{ asset(MessageDisplay.author.picture) }}" alt="" class="ticket_img">
                                {% endif %}
                            </div>
                            <div class="client_info">
                                <p>{{ MessageDisplay.author.lastname }} {{ MessageDisplay.author.firstname }}</p>
                                {% if MessageDisplay.author.roles[0] == 'ROLE_ADMIN' %}
                                <p>{% if config == null %}De l'équipe Koala Ticket{% else %}{{config.staffName}}{% endif %}</p>
                                {% else %}
                                <p>Client</p>
                                {% endif %}
                            </div>
                        </div>
                        <div>
                        {% if MessageDisplay.author.roles[0] == 'ROLE_ADMIN' %}
                            <p class="response_date" style="background-color:white !important;color:black;">{{ MessageDisplay.date|date('d/m/Y à H\\hi') }}</p>
                        {% else %}
                            <p class="response_date" style="{% if config == null %}{% else %}background-color:{{config.color}} !important;{% endif %}">{{ MessageDisplay.date|date('d/m/Y à H\\hi') }}</p>
                        {% endif %}
                        </div>
                    </div>
                    <div class="ticket_line"></div>
                    <div class="ticket_client_message">
                        <p>{{ MessageDisplay.content|nl2br }}</p>
                    </div>
                </div>

        {# Affichage d'une boite de message CLIENT  #}
        {% endfor %}

        {# Affichage du formulaire de réponse si le ticket n'est pas fermé #}
        {% if actualTicket.statement != 'fermé' %}
            <div class="client_response">
                <form name="create_message" method="post">
                    <div id="create_message">
                        <div class="error_msg">
                            {{ form_errors(form.content) }}
                        </div>
                        <div>
                            {{ form_widget(form.content) }}
                        </div>
                        <div>
                            <button type="submit" id="create_message_save" name="create_message[save]" class="login_button input_size_ticket submit_top" style="{% if config == null %}{% else %}background-color:{{config.color}};{% endif %}">Répondre</button>
                        </div>
                        {{ form_row(form._token) }}
                    </div>
                </form>
            </div>
            </div>
            <div class="statut_btn statut_btn_width">
                <p>{{ actualTicket.creationDate|date('d/m/Y à H\\hi') }}</p>
                <p class="reset_margin">Actuellement {{actualTicket.Statement}}</p>
            </div>
            {# Si le ticket est fermé, réponse d'un bot #}
            {% else %}
                <div class="client_response green" style="{% if config == null %}{% else %}background-color:{{config.color}} !important;{% endif %}">
                    <div class="ticket_client_message">
                        <p style="text-align:center;font-size:14px">Le ticket est actuellement fermé.<br>Si vous pensez qu'il s'agit d'une erreur, ouvrez un nouveau ticket.<br>Indiquez alors la référence de ce ticket.</p>
                    </div>
                </div>
        {% endif %}
        </div>
    </section>
{% endblock %}